### PR TITLE
Correct documentation

### PR DESCRIPTION
**Pull request by davekrupinski**
Updated the documentation with the correct function call.

### CODE REVIEW

**Comment by ajwhite** [comment]
Oh man.. silly me. Thanks @davekrupinski.

Now I'm sitting here contemplating if I should rename the plugin method name to `stockQuotes()` versus `stockQuote()`. 

The project is `jquery-stockquotes`, so I feel that `$('x').stockQuotes()` would be more consistent. But then I question if pluralization is the right way to name something like this.

**Comment by atticoos** [comment]
Oh man.. silly me. Thanks @davekrupinski.

Now I'm sitting here contemplating if I should rename the plugin method name to `stockQuotes()` versus `stockQuote()`. 

The project is `jquery-stockquotes`, so I feel that `$('x').stockQuotes()` would be more consistent. But then I question if pluralization is the right way to name something like this.

**Comment by atticoos** [comment]
Let me think about this for a little bit, I'll get back to you on merging

**Comment by atticoos** [comment]
I ended up adding an alias for the plural form.

Thanks for pointing this out and looking to fix it. I'm going to keep everything as is with documentation referring to `.stockQuotes()` for naming consistency.

**Pull request closed without merging**
